/**
 * VOC Flow Control - Orchestrateur
 * 
 * Cœur du système multi-agents
 */

const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

class AgentOrchestrator {
  constructor() {
    this.agents = new Map();
    this.tasks = [];
    this.skills = new Map();
    this.loadAgents();
    this.loadSkills();
  }

  loadAgents() {
    const agentsDir = path.join(__dirname, '..', 'agents');
    const files = fs.readdirSync(agentsDir).filter(f => f.startsWith('AGENT-'));
    
    files.forEach(file => {
      const name = file.replace('AGENT-', '').replace('.md', '');
      this.agents.set(name, {
        name,
        status: 'idle',
        lastHeartbeat: Date.now(),
        tasks: [],
        skills: []
      });
    });

    console.log(`✅ ${this.agents.size} agents chargés`);
  }

  loadSkills() {
    // Charger les 30+ skills de base
    const coreSkills = [
      'code-review', 'dependency-check', 'security-scan', 'performance-test',
      'documentation-gen', 'test-generator', 'refactoring', 'deployment',
      'monitoring', 'backup-restore', 'react-optimization', 'css-architecture',
      'responsive-design', 'accessibility-audit', 'storybook-setup',
      'pwa-generator', 'ui-testing', 'bundle-analysis', 'api-design',
      'database-optimization', 'caching-strategy', 'microservices-setup',
      'queue-management', 'auth-implementation', 'rate-limiting',
      'docker-containerization', 'ci-cd-pipeline', 'kubernetes-deployment',
      'infrastructure-as-code', 'log-aggregation'
    ];

    coreSkills.forEach(skill => {
      this.skills.set(skill, {
        name: skill,
        available: true,
        usage: 0
      });
    });

    console.log(`✅ ${this.skills.size} skills chargées`);
  }

  // Trouver le meilleur skill pour une tâche
  findBestSkill(task) {
    // Algorithme de matching simple
    const matches = [];
    for (const [name, skill] of this.skills) {
      if (task.toLowerCase().includes(name.toLowerCase())) {
        matches.push(skill);
      }
    }
    return matches.length > 0 ? matches[0] : null;
  }

  // Générer un nouvel agent si nécessaire
  generateSpecializedAgent(task, parentAgent) {
    const complexity = this.assessComplexity(task);
    
    if (complexity > 7) {
      const agentName = `${parentAgent}-${Date.now()}`;
      console.log(`🆕 Génération agent spécialisé: ${agentName}`);
      
      // Créer le fichier agent
      const agentContent = this.generateAgentFile(agentName, task, parentAgent);
      fs.writeFileSync(
        path.join(__dirname, '..', 'agents', `AGENT-${agentName.toUpperCase()}.md`),
        agentContent
      );
      
      return agentName;
    }
    
    return parentAgent;
  }

  assessComplexity(task) {
    // Évaluation simple de la complexité
    let score = 0;
    if (task.includes('architecture')) score += 3;
    if (task.includes('microservices')) score += 4;
    if (task.includes('kubernetes')) score += 3;
    if (task.includes('complex')) score += 2;
    if (task.includes('migration')) score += 3;
    return Math.min(score, 10);
  }

  generateAgentFile(name, task, parent) {
    return `# AGENT-${name.toUpperCase()}.md — Agent Spécialisé

## Identité
- **Nom:** ${name}
- **Type:** Agent spécialisé généré automatiquement
- **Tâche:** ${task}
- **Parent:** ${parent}

## Mission
Agent créé pour traiter une tâche complexe nécessitant une expertise spécifique.

## Capacités
- Traitement de la tâche assignée
- Création de skills temporaires si nécessaire
- Reporting à l'agent parent

## Auto-Destruction
Cet agent sera supprimé après complétion de sa tâche.

---
*Généré le ${new Date().toISOString()}*
`;
  }

  // Trouver ou créer une skill
  ensureSkill(skillName, category) {
    if (!this.skills.has(skillName)) {
      console.log(`🔧 Création nouvelle skill: ${skillName}`);
      this.skills.set(skillName, {
        name: skillName,
        category,
        available: true,
        usage: 0,
        autoGenerated: true
      });
      
      // Créer le fichier skill
      this.createSkillFile(skillName, category);
    }
    return this.skills.get(skillName);
  }

  createSkillFile(name, category) {
    const skillDir = path.join(__dirname, '..', 'skills', category, name);
    fs.mkdirSync(skillDir, { recursive: true });
    
    const skillContent = `name: ${name}
category: ${category}
description: Skill auto-générée pour ${name}
version: 1.0.0
author: AgentOrchestrator
auto_generated: true
created_at: ${new Date().toISOString()}

dependencies: []
inputs: []
outputs: []
template: "# Auto-generated skill"
`;
    
    fs.writeFileSync(path.join(skillDir, 'skill.yaml'), skillContent);
  }

  start() {
    console.log('🚀 Orchestrateur démarré');
    console.log(`📊 ${this.agents.size} agents | ${this.skills.size} skills`);
    
    // Heartbeat monitoring
    setInterval(() => {
      this.checkAgentHealth();
    }, 60000);
  }

  checkAgentHealth() {
    const now = Date.now();
    for (const [name, agent] of this.agents) {
      const lastSeen = now - agent.lastHeartbeat;
      if (lastSeen > 300000) { // 5 minutes
        console.log(`⚠️ Agent ${name} non répondeur (${Math.round(lastSeen/1000)}s)`);
      }
    }
  }
}

// Démarrer si exécuté directement
if (require.main === module) {
  const orchestrator = new AgentOrchestrator();
  orchestrator.start();
}

module.exports = AgentOrchestrator;
